version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    command: >
      sh -c "uvicorn server:app --host 0.0.0.0 --port 8000 --reload &
             streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    restart: always
